"""Sample test — auto-generated by goal."""

import sys
from pathlib import Path


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    import src  # noqa: F401
    from src.main import Supervisor  # noqa: F401
